#!/bin/sh
set -e
if [ -d /var/lib/tomcat6 ] ; then
	ln -snf /usr/share/java/canl-java-tomcat.jar /var/lib/tomcat6/common/canl-java-tomcat.jar
	
	if [ -f /usr/share/java/bcprov-1.46.jar ] ; then 
		ln -snf /usr/share/java/bcprov-1.46.jar /var/lib/tomcat6/common/bcprov.jar
	else
		echo "/usr/share/java/bcprov-1.46.jar not found, cannot link it to the tomcat server/lib"
	fi
	if [ -f /usr/share/java/canl.jar ] ; then 
		ln -snf /usr/share/java/canl.jar /var/lib/tomcat6/common/canl.jar
	else
		echo /usr/share/java/canl.jar not found, cannot link it to the tomcat server/lib
	fi
	if [ -f /usr/share/java/commons-io.jar ] ; then 
		ln -snf /usr/share/java/commons-io.jar /var/lib/tomcat6/common/commons-io.jar
	else
		echo "/usr/share/java/commons-io.jar not found, cannot link it to the tomcat server/lib"
	fi	
else
	echo No tomcat6 installation found, link the necessary libraries to tomcat6/common yourself.
fi
#DEBHELPER#